# Generated by Django 3.2.3 on 2021-05-21 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artist_name',
            field=models.CharField(default='Taylor Swift', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='date_listened_to',
            field=models.DateField(default=datetime.date(2021, 5, 21)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='spotify_link',
            field=models.CharField(default='NA', max_length=200),
            preserve_default=False,
        ),
    ]
