# Generated by Django 3.2.3 on 2021-05-21 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_auto_20210521_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='album',
            name='release_date',
        ),
    ]
