# Generated by Django 3.2.3 on 2021-05-22 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_auto_20210521_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(default='let-love-rule'),
            preserve_default=False,
        ),
    ]
